# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
